### PR TITLE
feat: Upgrade aspect ratio

### PR DESCRIPTION
**Pull request by guilhermelimak**
I noticed you're using a deprecated aspect ratio in your config. I have updated it so you can get moar fragz.

You can read on why this is bad here: https://medium.com/@lurppis/the-16-9-vs-4-3-aspect-ratio-argument-667bd771b342.

With this new improvements, your screen will look like this:

You're welcome.

### CODE REVIEW

**Comment by sShayron** [comment]
Tas loco mano, vou usar isso nao, isso e monitor ultrawide?

**Comment by Rafael-Martins** [comment]
Very great changes man, i would approve!

**Comment by Rafael-Martins** [comment]
Man, why we closed this?

**Comment by armand1m** [comment]
I think this should be reopened

**Pull request closed without merging**
